[tool:pytest]
addopts =  --ckan-ini test.ini
testpaths = ckanext/oauth2/tests
python_files = test_*.py
python_functions = test_*
python_classes = Test*
markers =
    ckan_config: marks tests that need CKAN configuration
    usefixtures: automatically use fixtures
filterwarnings =
    ignore::UserWarning
    ignore::DeprecationWarning